#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDD_interface_like
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parc_Auto")]
	public partial class Parc_AutoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAngajati(Angajati instance);
    partial void UpdateAngajati(Angajati instance);
    partial void DeleteAngajati(Angajati instance);
    partial void InsertIssue(Issue instance);
    partial void UpdateIssue(Issue instance);
    partial void DeleteIssue(Issue instance);
    partial void InsertMasini(Masini instance);
    partial void UpdateMasini(Masini instance);
    partial void DeleteMasini(Masini instance);
    partial void InsertSupplier(Supplier instance);
    partial void UpdateSupplier(Supplier instance);
    partial void DeleteSupplier(Supplier instance);
    partial void InsertOptiuni(Optiuni instance);
    partial void UpdateOptiuni(Optiuni instance);
    partial void DeleteOptiuni(Optiuni instance);
    partial void InsertVanzari(Vanzari instance);
    partial void UpdateVanzari(Vanzari instance);
    partial void DeleteVanzari(Vanzari instance);
    #endregion
		
		public Parc_AutoDataContext() : 
				base(global::BDD_interface_like.Properties.Settings.Default.Parc_AutoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Parc_AutoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Parc_AutoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Parc_AutoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Parc_AutoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin_user> Admin_users
		{
			get
			{
				return this.GetTable<Admin_user>();
			}
		}
		
		public System.Data.Linq.Table<Angajati> Angajatis
		{
			get
			{
				return this.GetTable<Angajati>();
			}
		}
		
		public System.Data.Linq.Table<Cars_Issue> Cars_Issues
		{
			get
			{
				return this.GetTable<Cars_Issue>();
			}
		}
		
		public System.Data.Linq.Table<Issue> Issues
		{
			get
			{
				return this.GetTable<Issue>();
			}
		}
		
		public System.Data.Linq.Table<Masini> Masinis
		{
			get
			{
				return this.GetTable<Masini>();
			}
		}
		
		public System.Data.Linq.Table<Supplier> Suppliers
		{
			get
			{
				return this.GetTable<Supplier>();
			}
		}
		
		public System.Data.Linq.Table<Optiuni> Optiunis
		{
			get
			{
				return this.GetTable<Optiuni>();
			}
		}
		
		public System.Data.Linq.Table<Vanzari> Vanzaris
		{
			get
			{
				return this.GetTable<Vanzari>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin_users")]
	public partial class Admin_user
	{
		
		private System.Nullable<int> _Admin_ID;
		
		private string _Admin_name;
		
		private string _Username;
		
		private string _Password;
		
		public Admin_user()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_ID", DbType="Int")]
		public System.Nullable<int> Admin_ID
		{
			get
			{
				return this._Admin_ID;
			}
			set
			{
				if ((this._Admin_ID != value))
				{
					this._Admin_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_name", DbType="NVarChar(50)")]
		public string Admin_name
		{
			get
			{
				return this._Admin_name;
			}
			set
			{
				if ((this._Admin_name != value))
				{
					this._Admin_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Angajati")]
	public partial class Angajati : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AngajatID;
		
		private string _Nume;
		
		private string _Functie;
		
		private System.Nullable<double> _Salariu_baza;
		
		private EntitySet<Vanzari> _Vanzaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAngajatIDChanging(int value);
    partial void OnAngajatIDChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnFunctieChanging(string value);
    partial void OnFunctieChanged();
    partial void OnSalariu_bazaChanging(System.Nullable<double> value);
    partial void OnSalariu_bazaChanged();
    #endregion
		
		public Angajati()
		{
			this._Vanzaris = new EntitySet<Vanzari>(new Action<Vanzari>(this.attach_Vanzaris), new Action<Vanzari>(this.detach_Vanzaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AngajatID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AngajatID
		{
			get
			{
				return this._AngajatID;
			}
			set
			{
				if ((this._AngajatID != value))
				{
					this.OnAngajatIDChanging(value);
					this.SendPropertyChanging();
					this._AngajatID = value;
					this.SendPropertyChanged("AngajatID");
					this.OnAngajatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NVarChar(50)")]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Functie", DbType="NVarChar(50)")]
		public string Functie
		{
			get
			{
				return this._Functie;
			}
			set
			{
				if ((this._Functie != value))
				{
					this.OnFunctieChanging(value);
					this.SendPropertyChanging();
					this._Functie = value;
					this.SendPropertyChanged("Functie");
					this.OnFunctieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salariu_baza", DbType="Float")]
		public System.Nullable<double> Salariu_baza
		{
			get
			{
				return this._Salariu_baza;
			}
			set
			{
				if ((this._Salariu_baza != value))
				{
					this.OnSalariu_bazaChanging(value);
					this.SendPropertyChanging();
					this._Salariu_baza = value;
					this.SendPropertyChanged("Salariu_baza");
					this.OnSalariu_bazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Vanzari", Storage="_Vanzaris", ThisKey="AngajatID", OtherKey="Angajat_ID")]
		public EntitySet<Vanzari> Vanzaris
		{
			get
			{
				return this._Vanzaris;
			}
			set
			{
				this._Vanzaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vanzaris(Vanzari entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = this;
		}
		
		private void detach_Vanzaris(Vanzari entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cars_Issues")]
	public partial class Cars_Issue
	{
		
		private int _ID_car;
		
		private int _ID_Issue;
		
		public Cars_Issue()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_car", DbType="Int NOT NULL")]
		public int ID_car
		{
			get
			{
				return this._ID_car;
			}
			set
			{
				if ((this._ID_car != value))
				{
					this._ID_car = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Issue", DbType="Int NOT NULL")]
		public int ID_Issue
		{
			get
			{
				return this._ID_Issue;
			}
			set
			{
				if ((this._ID_Issue != value))
				{
					this._ID_Issue = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Issues")]
	public partial class Issue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Issues;
		
		private string _Denumire;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_IssuesChanging(int value);
    partial void OnID_IssuesChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    #endregion
		
		public Issue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Issues", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Issues
		{
			get
			{
				return this._ID_Issues;
			}
			set
			{
				if ((this._ID_Issues != value))
				{
					this.OnID_IssuesChanging(value);
					this.SendPropertyChanging();
					this._ID_Issues = value;
					this.SendPropertyChanged("ID_Issues");
					this.OnID_IssuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="NVarChar(50)")]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Masini")]
	public partial class Masini : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Masina;
		
		private System.Nullable<int> _ID_Suppliers;
		
		private string _Marca;
		
		private string _Model;
		
		private string _VIN;
		
		private System.Nullable<int> _An_Fabricatie;
		
		private System.Nullable<double> _Pret_Vanzare;
		
		private EntitySet<Optiuni> _Optiunis;
		
		private EntityRef<Supplier> _Supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MasinaChanging(int value);
    partial void OnID_MasinaChanged();
    partial void OnID_SuppliersChanging(System.Nullable<int> value);
    partial void OnID_SuppliersChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnVINChanging(string value);
    partial void OnVINChanged();
    partial void OnAn_FabricatieChanging(System.Nullable<int> value);
    partial void OnAn_FabricatieChanged();
    partial void OnPret_VanzareChanging(System.Nullable<double> value);
    partial void OnPret_VanzareChanged();
    #endregion
		
		public Masini()
		{
			this._Optiunis = new EntitySet<Optiuni>(new Action<Optiuni>(this.attach_Optiunis), new Action<Optiuni>(this.detach_Optiunis));
			this._Supplier = default(EntityRef<Supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Masina", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Masina
		{
			get
			{
				return this._ID_Masina;
			}
			set
			{
				if ((this._ID_Masina != value))
				{
					this.OnID_MasinaChanging(value);
					this.SendPropertyChanging();
					this._ID_Masina = value;
					this.SendPropertyChanged("ID_Masina");
					this.OnID_MasinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Suppliers", DbType="Int")]
		public System.Nullable<int> ID_Suppliers
		{
			get
			{
				return this._ID_Suppliers;
			}
			set
			{
				if ((this._ID_Suppliers != value))
				{
					if (this._Supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SuppliersChanging(value);
					this.SendPropertyChanging();
					this._ID_Suppliers = value;
					this.SendPropertyChanged("ID_Suppliers");
					this.OnID_SuppliersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(50)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(50)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIN", DbType="NVarChar(50)")]
		public string VIN
		{
			get
			{
				return this._VIN;
			}
			set
			{
				if ((this._VIN != value))
				{
					this.OnVINChanging(value);
					this.SendPropertyChanging();
					this._VIN = value;
					this.SendPropertyChanged("VIN");
					this.OnVINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_An_Fabricatie", DbType="Int")]
		public System.Nullable<int> An_Fabricatie
		{
			get
			{
				return this._An_Fabricatie;
			}
			set
			{
				if ((this._An_Fabricatie != value))
				{
					this.OnAn_FabricatieChanging(value);
					this.SendPropertyChanging();
					this._An_Fabricatie = value;
					this.SendPropertyChanged("An_Fabricatie");
					this.OnAn_FabricatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret_Vanzare", DbType="Float")]
		public System.Nullable<double> Pret_Vanzare
		{
			get
			{
				return this._Pret_Vanzare;
			}
			set
			{
				if ((this._Pret_Vanzare != value))
				{
					this.OnPret_VanzareChanging(value);
					this.SendPropertyChanging();
					this._Pret_Vanzare = value;
					this.SendPropertyChanged("Pret_Vanzare");
					this.OnPret_VanzareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Masini_Optiuni", Storage="_Optiunis", ThisKey="ID_Masina", OtherKey="ID_Masina")]
		public EntitySet<Optiuni> Optiunis
		{
			get
			{
				return this._Optiunis;
			}
			set
			{
				this._Optiunis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Masini", Storage="_Supplier", ThisKey="ID_Suppliers", OtherKey="ID_Suppliers", IsForeignKey=true, DeleteRule="CASCADE")]
		public Supplier Supplier
		{
			get
			{
				return this._Supplier.Entity;
			}
			set
			{
				Supplier previousValue = this._Supplier.Entity;
				if (((previousValue != value) 
							|| (this._Supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Supplier.Entity = null;
						previousValue.Masinis.Remove(this);
					}
					this._Supplier.Entity = value;
					if ((value != null))
					{
						value.Masinis.Add(this);
						this._ID_Suppliers = value.ID_Suppliers;
					}
					else
					{
						this._ID_Suppliers = default(Nullable<int>);
					}
					this.SendPropertyChanged("Supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Optiunis(Optiuni entity)
		{
			this.SendPropertyChanging();
			entity.Masini = this;
		}
		
		private void detach_Optiunis(Optiuni entity)
		{
			this.SendPropertyChanging();
			entity.Masini = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Suppliers")]
	public partial class Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Suppliers;
		
		private string _Company_Name;
		
		private string _Country;
		
		private string _Region;
		
		private string _Address;
		
		private string _Phone;
		
		private string _Email;
		
		private EntitySet<Masini> _Masinis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SuppliersChanging(int value);
    partial void OnID_SuppliersChanged();
    partial void OnCompany_NameChanging(string value);
    partial void OnCompany_NameChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Supplier()
		{
			this._Masinis = new EntitySet<Masini>(new Action<Masini>(this.attach_Masinis), new Action<Masini>(this.detach_Masinis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Suppliers", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Suppliers
		{
			get
			{
				return this._ID_Suppliers;
			}
			set
			{
				if ((this._ID_Suppliers != value))
				{
					this.OnID_SuppliersChanging(value);
					this.SendPropertyChanging();
					this._ID_Suppliers = value;
					this.SendPropertyChanged("ID_Suppliers");
					this.OnID_SuppliersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_Name", DbType="NVarChar(50)")]
		public string Company_Name
		{
			get
			{
				return this._Company_Name;
			}
			set
			{
				if ((this._Company_Name != value))
				{
					this.OnCompany_NameChanging(value);
					this.SendPropertyChanging();
					this._Company_Name = value;
					this.SendPropertyChanged("Company_Name");
					this.OnCompany_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(50)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Masini", Storage="_Masinis", ThisKey="ID_Suppliers", OtherKey="ID_Suppliers")]
		public EntitySet<Masini> Masinis
		{
			get
			{
				return this._Masinis;
			}
			set
			{
				this._Masinis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Masinis(Masini entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = this;
		}
		
		private void detach_Masinis(Masini entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Optiuni")]
	public partial class Optiuni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_optiune;
		
		private int _ID_Masina;
		
		private string _Climatizare;
		
		private string _Faruri;
		
		private string _Tapiterie;
		
		private string _Culoare;
		
		private System.Nullable<bool> _Tractiune4x4;
		
		private System.Nullable<bool> _Navigatie;
		
		private System.Nullable<bool> _Avariat;
		
		private System.Nullable<bool> _Senzori_parcare;
		
		private System.Nullable<bool> _Faruri_ceata;
		
		private System.Nullable<bool> _Scaune_incalzite;
		
		private System.Nullable<bool> _Comenzi_volan;
		
		private System.Nullable<bool> _Cruise_control;
		
		private EntityRef<Masini> _Masini;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_optiuneChanging(int value);
    partial void OnID_optiuneChanged();
    partial void OnID_MasinaChanging(int value);
    partial void OnID_MasinaChanged();
    partial void OnClimatizareChanging(string value);
    partial void OnClimatizareChanged();
    partial void OnFaruriChanging(string value);
    partial void OnFaruriChanged();
    partial void OnTapiterieChanging(string value);
    partial void OnTapiterieChanged();
    partial void OnCuloareChanging(string value);
    partial void OnCuloareChanged();
    partial void OnTractiune4x4Changing(System.Nullable<bool> value);
    partial void OnTractiune4x4Changed();
    partial void OnNavigatieChanging(System.Nullable<bool> value);
    partial void OnNavigatieChanged();
    partial void OnAvariatChanging(System.Nullable<bool> value);
    partial void OnAvariatChanged();
    partial void OnSenzori_parcareChanging(System.Nullable<bool> value);
    partial void OnSenzori_parcareChanged();
    partial void OnFaruri_ceataChanging(System.Nullable<bool> value);
    partial void OnFaruri_ceataChanged();
    partial void OnScaune_incalziteChanging(System.Nullable<bool> value);
    partial void OnScaune_incalziteChanged();
    partial void OnComenzi_volanChanging(System.Nullable<bool> value);
    partial void OnComenzi_volanChanged();
    partial void OnCruise_controlChanging(System.Nullable<bool> value);
    partial void OnCruise_controlChanged();
    #endregion
		
		public Optiuni()
		{
			this._Masini = default(EntityRef<Masini>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_optiune", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_optiune
		{
			get
			{
				return this._ID_optiune;
			}
			set
			{
				if ((this._ID_optiune != value))
				{
					this.OnID_optiuneChanging(value);
					this.SendPropertyChanging();
					this._ID_optiune = value;
					this.SendPropertyChanged("ID_optiune");
					this.OnID_optiuneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Masina", DbType="Int NOT NULL")]
		public int ID_Masina
		{
			get
			{
				return this._ID_Masina;
			}
			set
			{
				if ((this._ID_Masina != value))
				{
					if (this._Masini.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MasinaChanging(value);
					this.SendPropertyChanging();
					this._ID_Masina = value;
					this.SendPropertyChanged("ID_Masina");
					this.OnID_MasinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Climatizare", DbType="NVarChar(50)")]
		public string Climatizare
		{
			get
			{
				return this._Climatizare;
			}
			set
			{
				if ((this._Climatizare != value))
				{
					this.OnClimatizareChanging(value);
					this.SendPropertyChanging();
					this._Climatizare = value;
					this.SendPropertyChanged("Climatizare");
					this.OnClimatizareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faruri", DbType="NVarChar(50)")]
		public string Faruri
		{
			get
			{
				return this._Faruri;
			}
			set
			{
				if ((this._Faruri != value))
				{
					this.OnFaruriChanging(value);
					this.SendPropertyChanging();
					this._Faruri = value;
					this.SendPropertyChanged("Faruri");
					this.OnFaruriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tapiterie", DbType="NVarChar(50)")]
		public string Tapiterie
		{
			get
			{
				return this._Tapiterie;
			}
			set
			{
				if ((this._Tapiterie != value))
				{
					this.OnTapiterieChanging(value);
					this.SendPropertyChanging();
					this._Tapiterie = value;
					this.SendPropertyChanged("Tapiterie");
					this.OnTapiterieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Culoare", DbType="NVarChar(50)")]
		public string Culoare
		{
			get
			{
				return this._Culoare;
			}
			set
			{
				if ((this._Culoare != value))
				{
					this.OnCuloareChanging(value);
					this.SendPropertyChanging();
					this._Culoare = value;
					this.SendPropertyChanged("Culoare");
					this.OnCuloareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractiune4x4", DbType="Bit")]
		public System.Nullable<bool> Tractiune4x4
		{
			get
			{
				return this._Tractiune4x4;
			}
			set
			{
				if ((this._Tractiune4x4 != value))
				{
					this.OnTractiune4x4Changing(value);
					this.SendPropertyChanging();
					this._Tractiune4x4 = value;
					this.SendPropertyChanged("Tractiune4x4");
					this.OnTractiune4x4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Navigatie", DbType="Bit")]
		public System.Nullable<bool> Navigatie
		{
			get
			{
				return this._Navigatie;
			}
			set
			{
				if ((this._Navigatie != value))
				{
					this.OnNavigatieChanging(value);
					this.SendPropertyChanging();
					this._Navigatie = value;
					this.SendPropertyChanged("Navigatie");
					this.OnNavigatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avariat", DbType="Bit")]
		public System.Nullable<bool> Avariat
		{
			get
			{
				return this._Avariat;
			}
			set
			{
				if ((this._Avariat != value))
				{
					this.OnAvariatChanging(value);
					this.SendPropertyChanging();
					this._Avariat = value;
					this.SendPropertyChanged("Avariat");
					this.OnAvariatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senzori_parcare", DbType="Bit")]
		public System.Nullable<bool> Senzori_parcare
		{
			get
			{
				return this._Senzori_parcare;
			}
			set
			{
				if ((this._Senzori_parcare != value))
				{
					this.OnSenzori_parcareChanging(value);
					this.SendPropertyChanging();
					this._Senzori_parcare = value;
					this.SendPropertyChanged("Senzori_parcare");
					this.OnSenzori_parcareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faruri_ceata", DbType="Bit")]
		public System.Nullable<bool> Faruri_ceata
		{
			get
			{
				return this._Faruri_ceata;
			}
			set
			{
				if ((this._Faruri_ceata != value))
				{
					this.OnFaruri_ceataChanging(value);
					this.SendPropertyChanging();
					this._Faruri_ceata = value;
					this.SendPropertyChanged("Faruri_ceata");
					this.OnFaruri_ceataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scaune_incalzite", DbType="Bit")]
		public System.Nullable<bool> Scaune_incalzite
		{
			get
			{
				return this._Scaune_incalzite;
			}
			set
			{
				if ((this._Scaune_incalzite != value))
				{
					this.OnScaune_incalziteChanging(value);
					this.SendPropertyChanging();
					this._Scaune_incalzite = value;
					this.SendPropertyChanged("Scaune_incalzite");
					this.OnScaune_incalziteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comenzi_volan", DbType="Bit")]
		public System.Nullable<bool> Comenzi_volan
		{
			get
			{
				return this._Comenzi_volan;
			}
			set
			{
				if ((this._Comenzi_volan != value))
				{
					this.OnComenzi_volanChanging(value);
					this.SendPropertyChanging();
					this._Comenzi_volan = value;
					this.SendPropertyChanged("Comenzi_volan");
					this.OnComenzi_volanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cruise_control", DbType="Bit")]
		public System.Nullable<bool> Cruise_control
		{
			get
			{
				return this._Cruise_control;
			}
			set
			{
				if ((this._Cruise_control != value))
				{
					this.OnCruise_controlChanging(value);
					this.SendPropertyChanging();
					this._Cruise_control = value;
					this.SendPropertyChanged("Cruise_control");
					this.OnCruise_controlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Masini_Optiuni", Storage="_Masini", ThisKey="ID_Masina", OtherKey="ID_Masina", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Masini Masini
		{
			get
			{
				return this._Masini.Entity;
			}
			set
			{
				Masini previousValue = this._Masini.Entity;
				if (((previousValue != value) 
							|| (this._Masini.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Masini.Entity = null;
						previousValue.Optiunis.Remove(this);
					}
					this._Masini.Entity = value;
					if ((value != null))
					{
						value.Optiunis.Add(this);
						this._ID_Masina = value.ID_Masina;
					}
					else
					{
						this._ID_Masina = default(int);
					}
					this.SendPropertyChanged("Masini");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vanzari")]
	public partial class Vanzari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Vanzari;
		
		private int _Angajat_ID;
		
		private string _VIN;
		
		private string _Client;
		
		private string _Vanzator;
		
		private System.Nullable<double> _Pret_vanzare;
		
		private System.Nullable<System.DateTime> _Data;
		
		private EntityRef<Angajati> _Angajati;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VanzariChanging(int value);
    partial void OnID_VanzariChanged();
    partial void OnAngajat_IDChanging(int value);
    partial void OnAngajat_IDChanged();
    partial void OnVINChanging(string value);
    partial void OnVINChanged();
    partial void OnClientChanging(string value);
    partial void OnClientChanged();
    partial void OnVanzatorChanging(string value);
    partial void OnVanzatorChanged();
    partial void OnPret_vanzareChanging(System.Nullable<double> value);
    partial void OnPret_vanzareChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    #endregion
		
		public Vanzari()
		{
			this._Angajati = default(EntityRef<Angajati>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vanzari", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Vanzari
		{
			get
			{
				return this._ID_Vanzari;
			}
			set
			{
				if ((this._ID_Vanzari != value))
				{
					this.OnID_VanzariChanging(value);
					this.SendPropertyChanging();
					this._ID_Vanzari = value;
					this.SendPropertyChanged("ID_Vanzari");
					this.OnID_VanzariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Angajat_ID", DbType="Int NOT NULL")]
		public int Angajat_ID
		{
			get
			{
				return this._Angajat_ID;
			}
			set
			{
				if ((this._Angajat_ID != value))
				{
					if (this._Angajati.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAngajat_IDChanging(value);
					this.SendPropertyChanging();
					this._Angajat_ID = value;
					this.SendPropertyChanged("Angajat_ID");
					this.OnAngajat_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VIN
		{
			get
			{
				return this._VIN;
			}
			set
			{
				if ((this._VIN != value))
				{
					this.OnVINChanging(value);
					this.SendPropertyChanging();
					this._VIN = value;
					this.SendPropertyChanged("VIN");
					this.OnVINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="NVarChar(50)")]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this.OnClientChanging(value);
					this.SendPropertyChanging();
					this._Client = value;
					this.SendPropertyChanged("Client");
					this.OnClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vanzator", DbType="NVarChar(50)")]
		public string Vanzator
		{
			get
			{
				return this._Vanzator;
			}
			set
			{
				if ((this._Vanzator != value))
				{
					this.OnVanzatorChanging(value);
					this.SendPropertyChanging();
					this._Vanzator = value;
					this.SendPropertyChanged("Vanzator");
					this.OnVanzatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret_vanzare", DbType="Float")]
		public System.Nullable<double> Pret_vanzare
		{
			get
			{
				return this._Pret_vanzare;
			}
			set
			{
				if ((this._Pret_vanzare != value))
				{
					this.OnPret_vanzareChanging(value);
					this.SendPropertyChanging();
					this._Pret_vanzare = value;
					this.SendPropertyChanged("Pret_vanzare");
					this.OnPret_vanzareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Vanzari", Storage="_Angajati", ThisKey="Angajat_ID", OtherKey="AngajatID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Angajati Angajati
		{
			get
			{
				return this._Angajati.Entity;
			}
			set
			{
				Angajati previousValue = this._Angajati.Entity;
				if (((previousValue != value) 
							|| (this._Angajati.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Angajati.Entity = null;
						previousValue.Vanzaris.Remove(this);
					}
					this._Angajati.Entity = value;
					if ((value != null))
					{
						value.Vanzaris.Add(this);
						this._Angajat_ID = value.AngajatID;
					}
					else
					{
						this._Angajat_ID = default(int);
					}
					this.SendPropertyChanged("Angajati");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
